version: '3'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${GATEWAY_PORT}:3000"
    container_name: ecommerce-gateway